### PR TITLE
Improve printError for startup error handling (#1902)

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
And now because of the rebase on the other repo this will have conflicts ^^

**Comment by estliberitas** [comment]
@soyuka That's why I wanted you to make changes in separate PR. :wink:

**Comment by soyuka** [comment]
We don't need to `callback({msg: err})` everywhere, only in the callaback that respond to CLI.startup.

I started some tests, I'll try to find time to finish this tonight.

**Comment by estliberitas** [comment]
So I did everything right last time. Good.

On Thu, Jan 21, 2016 at 12:50 PM Antoine Bluchet <notifications@github.com>
wrote:

> We don't need to callback({msg: err}) everywhere, only in the callaback
> that respond to CLI.startup.
>
> I started some tests, I'll try to find time to finish this tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estliberitas/PM2/pull/1#issuecomment-173519164>.
>
-- 
Sincerely,
Alexander Makarenko

**Comment by estliberitas** [comment]
Well, it seems that in final version of PR we're gonna see two commits called `Rework startup command code`. Is it OK? :+1:

**Comment by estliberitas** [comment]
@soyuka Could you do the following:
1. Squash your commits and stash them by any possible way
2. Revert to last commit before this branch
3. Do `git pull` in order to get my latest rebased commit.
4. Apply your changes in one commit + look at my comments.

This way we won't see 2 my commits (old one from this PR and rebased one) and repo will be cleaner without those "Merge blablabla" messages.

**Comment by soyuka** [comment]
Done but I've some more work on this

I'm adding your "private" functions to the scope to ease the tests implementation. I want to add tests for every function where it's possible (ie doesn't write an actual file). I might edit some things while doing this to get the best coverage we can have on this subject.

**Comment by estliberitas** [comment]
Okay, got the idea, thanks.

On Thu, Jan 21, 2016 at 2:21 PM Antoine Bluchet <notifications@github.com>
wrote:

> Done but I've some more work on this
>
> I'm adding your "private" functions to the scope to ease the tests
> implementation. I want to add tests for every function where it's possible
> (ie doesn't write an actual file). I might edit some things while doing
> this to get the best coverage we can have on this subject.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estliberitas/PM2/pull/1#issuecomment-173542049>.
>
-- 
Sincerely,
Alexander Makarenko

**Comment by estliberitas** [comment]
@soyuka So... Should I merge this and later you're to add more tests or should I wait now for those tests?

**Comment by soyuka** [comment]
It needs more tests and I didn't run them, it's not ready yet but I'm
adding them tonight.

**Comment by soyuka** [comment]
Better now :). If you don't see any mistakes feel free to merge!

**Comment by estliberitas** [comment]
@soyuka Coolio, man. :+1:

**Pull request merged**
